### ISSUE TITLE
Question: Production usage

### ISSUE THREAD

**Issue by shinzui** [robertdp/purescript-react-halo#2]
I just discovered this `react-halo` on the PureScript discourse, and I'm wondering if anyone is using it in production.

**Comment by robertdp** [comment]
Hi @shinzui,

My current work project has a large PureScript UI that was originally using my other library [`react-store`](https://github.com/robertdp/purescript-react-store). We migrated all the existing logic over to use `react-halo` instead, using an approach similar to this:

https://github.com/jonasbuntinx/purescript-react-realworld/blob/36ae26cae8b0cdc73666512f9b5023b0a3a53dcf/src/Conduit/Component/Store.purs#L18-L45

We intend to refactor our 2 or 3 most complex components to use forking and subscription management, and then refactor the rest to use lifecycle actions instead of `useEffectOnce` hooks, but we haven't had time yet.

There were also a couple of other projects that had been using `react-store` that I think were going to upgrade to `react-halo`, but I haven't heard the results yet.

**Comment by shinzui** [comment]
Thank you for the detailed answer and your work on various react libraries in the PS ecosystem. May I suggest mentioning that in the Readme to make it less risky for developers to adopt the library?
